
import React from 'react';
import { motion } from 'motion/react';
import { FileText, Shield, Info, Scale } from 'lucide-react';

const fadeInUpProps = {
  initial: { opacity: 0, y: 40 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-50px" },
  transition: { duration: 0.7, ease: "easeOut" }
};

export const TermsConditionsPage = () => (
  <motion.div {...fadeInUpProps} className="max-w-4xl mx-auto px-4 py-16">
    <div className="flex items-center gap-4 mb-8">
      <div className="w-12 h-12 bg-[#e31c3d]/10 rounded-xl flex items-center justify-center">
        <Scale className="text-[#e31c3d] w-6 h-6" />
      </div>
      <h1 className="text-4xl font-bold">Terms & Conditions</h1>
    </div>

    <div className="prose prose-slate max-w-none text-gray-600 space-y-6">
      <p>
        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>

      <p>
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name echokart.in ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
      </p>

      <p>
        The Platform is owned by EchoKart, a company incorporated under the Companies Act, 1956 with its registered office at Muzaffarnagar (hereinafter referred to as "Platform Owner", 'we', 'us', 'our').
      </p>

      <h2 className="text-2xl font-bold text-gray-900 mt-8">Agreement to Terms</h2>
      <p>
        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
      </p>

      <h2 className="text-2xl font-bold text-gray-900 mt-8">Services</h2>
      <p>
        These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
      </p>

      <h2 className="text-2xl font-bold text-gray-900 mt-8">Key Terms</h2>
      <ul className="list-disc pl-6 space-y-4">
        <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
        <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose.</li>
        <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.</li>
        <li>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents.</li>
        <li>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</li>
      </ul>

      <h2 className="text-2xl font-bold text-gray-900 mt-8">Indemnification</h2>
      <p>
        You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies.
      </p>

      <h2 className="text-2xl font-bold text-gray-900 mt-8">Governing Law</h2>
      <p>
        These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Muzaffarnagar and Uttar Pradesh.
      </p>
    </div>
  </motion.div>
);
